name: Topical build-test

on:
  push:
    branches:
      - topic/**
      - fix/**

jobs:
  build-test:
    uses: shredeagle/reusable-workflows/.github/workflows/main_build.yml@v2.3.2
    with:
      # Disable macOS
      # apple-clang 13 is being a little itch with deduction guides for template aliases.
      os: >-
        ["ubuntu-20.04", "windows-2022"]
    secrets:
      SHREDROBOT_GITHUB_TOKEN: ${{ secrets.SHREDROBOT_GITHUB_TOKEN }}
      ACTION_CACHENAME: ${{ secrets.ACTION_CACHENAME }}
      CONAN_USER_NAME: ${{ secrets.CONAN_USER_NAME }}
      CONAN_USER_PASSWORD: ${{ secrets.CONAN_USER_PASSWORD }}
